name: build
on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
      - 'support/**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run build script
        run: ./bin/build -vc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/*.zip
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: success() && startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: build/*.zip
